### ISSUE TITLE
When file exports a single class, displayName should be eq. to the file name

### ISSUE THREAD

**Issue by gajus** [babel-plugins/babel-plugin-react-display-name#1]
When a single file is used per module, most modules end up with derived `displayName` equal to `module.exports`. It would make sense to use file name instead, e.g.

```js
// PropTypes.js
/** @jsx React.DOM */

'use strict';

var React = require('react');

module.exports = React.createClass({
    render: function () {
        return <div />;
    }
});
```

In this case, `displayName` should be `PropTypes`.

Originally posted at https://github.com/facebook/react/issues/4429

**Comment by sebmck** [comment]
This already happens when using ES6 modules:

```javascript
export default React.createClass({
    render: function () {
        return <div />;
    }
});
```

I don't think it makes sense to give CommonJS modules any special behaviour, especially when they're going the way of the dodo.

**Comment by gajus** [comment]
> I don't think it makes sense to give CommonJS modules any special behaviour, especially when they're going the way of the dodo.

CommonJS style modules are being deprecated in node land?

**Comment by sebmck** [comment]
They're going to die as ES6 modules become more used. Babel is supposed to be a future oriented project and encouraging the use of CommonJS modules and special casing specific patterns doesn't make sense.
